# GameBoy Emulator Makefile

BIN = out/gameboy
INCLUDES = -I /usr/local/Cellar/sdl2/2.0.9_1/include/SDL2/ -L /usr/local/Cellar/sdl2/2.0.9_1/lib

SOURCES = gameboy.c bios.c screen.c sound.c platform.c inspector.c font.c

MAKE_OPTIONS = -Wall -std=c99 -g
#-O3 

LIBS = -lm -lSDL2

OPTIONS = $(LIBS)
#`sdl2-config --cflags --libs`

all:
	gcc $(MAKE_OPTIONS) $(SOURCES) $(INCLUDES) -o $(BIN) $(OPTIONS)

clean:
	rm -rf $(BIN)
